spring:
    application:
        name: Streaming App Backend

    datasource:
        url : jdbc:h2:mem:testdb
        username: anand
        password: anand5816
        driver-class-name: org.h2.Driver
        platform: h2

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        open-in-view=false:

    h2:
        console:
            enable:  true
            path: /h2-console

